stages:
  preprocess:
    cmd: python src/data_preprocessing.py --target "Class" --file "/Users/uditrawat/Desktop/RL/GAN-f/dataset/15_csv.csv" --output-dir data/processed
    deps:
      - src/data_preprocessing.py
      - /Users/uditrawat/Desktop/RL/GAN-f/dataset/15_csv.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/X_resampled.csv
      - data/processed/y_resampled.csv

  train_gan:
    cmd: python src/gan_training.py --input-dir data/processed --output models/generator.pkl
    deps:
      - src/gan_training.py
      - data/processed/X_train.csv
      - data/processed/X_resampled.csv
    outs:
      - models/generator.pkl

  augment_data:
    cmd: python src/augment_data.py --input-dir data/processed --output data/augmented --generator-model models/generator.pkl
    deps:
      - src/augment_data.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - models/generator.pkl
    outs:
      - data/augmented/X_augmented.csv
      - data/augmented/y_augmented.csv

  train_xgboost:
    cmd: python src/model_training.py --input data/augmented/X_augmented.csv --output results/metrics.csv
    deps:
      - src/model_training.py
      - data/augmented/X_augmented.csv
      - data/augmented/y_augmented.csv
    outs:
      - results/metrics.csv
